### ISSUE TITLE
Build a dedicated reference html page for univiz app

### ISSUE THREAD

**Issue by kaveh096** [ihsan314/step#16]
We should build a dedicated reference html page for univiz app to cite all the external resources we're using in the development and publishing. Here are few things form the top of my mind:

- [ ] Any css/html templates we use
- [ ] University dataset
- [ ] External APIs (if any)
- [ ] Internal APIs: Places, Charts, etc.

**Comment by ihsan314** [comment]
Will this be on each of our individual portfolios or on univiz? It seems it would be a little out of place here on my repo.

**Comment by kaveh096** [comment]
Sorry my bad. I'll move this to the univiz repo.
